INCLUDE 'emu8086.inc'
.MODEL SMALL 
.STACK 100H  

.DATA
    ID DB '221002063 $'
    ;NUM1 DB ?
	;NUM2 DB ?

.CODE 
 MAIN PROC
    MOV AX,@DATA
    MOV DS ,AX
    
    PRINTN 'CONTINIOUS LAB PERFORMANCE'
    ; PRINT MY STUDENT ID
    ; USER INPUT - 2 NUMBERS
    ; COMPARE THOSE NUMBERS
    ; SINCE MY ID IS ODD I HAVE TO PROVE N1 < N2 ? IF YES THEN PRINT SMALLER NUMBER
    ; IF SOMEONES ID IS EVEN THEN HE/SHE HAVE TO PROVE N1 > N2 ? IF YES THEN PRINT GREATER NUMBER
    
    PRINTN 'CONTINIOUS LAB PERFORMANCE'
    
    PRINTN ''
    PRINT 'FIRST NUMBER'
    MOV AH, 1
    INT 21H
    MOV BL, AL 
    ;SUB BL, 48    

    ; second input   
    PRINT ''
    PRINT 'SECOND NUMBER'
    MOV AH, 1
    INT 21H
    MOV BH, AL
    ;SUB BH, 48   
     
    CMP BL, BH
    JL LESS ; (JL) JUMP LESS  
    
    LEVEL:
        PRINTN ''
        PRINT 'SMALLER NUMBER: '
        MOV AH, 02H
        MOV DL, BH
        INT 21H
        JMP ENDOFFILE
    
    LESS:
        PRINTN ''
        PRINT 'SMALLER NUMBER: '
        MOV AH, 02H
        MOV DL, BL
        INT 21H
        
     ENDOFFILE:   
        PRINTN ''
        PRINT 'PROGRAM ENDS'
     
    
     MOV AH,4CH
     INT 21H
     MAIN ENDP
 END MAIN
    
    
